version: "3.8"

networks:
  persona_network:


volumes:
  db_volume:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:


services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: persona
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./config/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - persona_network

  sonarqube:
    image: sonarqube:community
    platform: linux/x86_64
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dbootstrap.system_call_filter=false"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - persona_network
