version: "3.8"

networks:
  persona-network:

volumes:
  db-volume:

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: persona
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - persona-network
