# Generated by Django 4.0.4 on 2022-06-19 09:46

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('external_id', models.CharField(max_length=36, verbose_name='external_id')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('uri', models.CharField(max_length=300, null=True, verbose_name='uri')),
                ('release_date', models.CharField(max_length=10, verbose_name='release_date')),
                ('release_date_precision', models.CharField(choices=[('Y', 'year'), ('M', 'month'), ('D', 'date')], default='M', max_length=1, verbose_name='release_date_precision')),
                ('total_tracks', models.PositiveSmallIntegerField(verbose_name='total_tracks')),
                ('href', models.CharField(max_length=2048, verbose_name='href')),
            ],
            options={
                'db_table': 'albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumExternalUrl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('url', models.URLField(max_length=2048, verbose_name='url')),
            ],
            options={
                'db_table': 'album_external_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'album_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('alpha_2', models.CharField(max_length=2, verbose_name='alpha_2')),
                ('alpha_3', models.CharField(max_length=3, verbose_name='alpha_3')),
                ('country_code', models.CharField(max_length=3, verbose_name='country_code')),
                ('iso_3166_2', models.CharField(max_length=13, verbose_name='iso_3166_2')),
                ('region', models.CharField(max_length=10, null=True, verbose_name='region')),
                ('sub_region', models.CharField(max_length=100, null=True, verbose_name='sub_region')),
                ('intermediate_region', models.CharField(max_length=100, null=True, verbose_name='intermediate_region')),
                ('region_code', models.CharField(max_length=3, null=True, verbose_name='region_code')),
                ('sub_region_code', models.CharField(max_length=3, null=True, verbose_name='sub_region_code')),
                ('intermediate_region_code', models.CharField(max_length=3, null=True, verbose_name='intermediate_region_code')),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('url', models.URLField(max_length=2048, unique=True, verbose_name='url')),
                ('height', models.IntegerField(default=300, verbose_name='height')),
                ('width', models.IntegerField(default=300, verbose_name='width')),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'db_table': 'sources',
                'managed': False,
            },
        ),
    ]
